### ISSUE TITLE
Error while deploying in Koyeb

### ISSUE THREAD

**Issue by whyhatewhen** [SilentDemonSD/FZBypassBot#27]
![image](https://github.com/SilentDemonSD/FZBypassBot/assets/78243989/a0e7f625-753a-428b-8287-7315e88e55a6)

please find the issue, thanks.

**Comment by Jegaa1** [comment]
> ![image](https://private-user-images.githubusercontent.com/78243989/293578457-a0e7f625-753a-428b-8287-7315e88e55a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODUzNDEsIm5iZiI6MTcwNDk4NTA0MSwicGF0aCI6Ii83ODI0Mzk4OS8yOTM1Nzg0NTctYTBlN2Y2MjUtNzUzYS00MjhiLTgyODctNzMxNWU4OGU1NWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE0NTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiOWJhZGYwMTFhYmY3NGY1ZDA3NzI4ZTlmNTM5NDgyZmM2MmZiZGYzMDRiN2IwYjdhYmRmNzA2YTZkNzFiZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t-y9EGs1dwg3KRUE53poBEMz3vRhz71ywytC50g-vE4)
> 
> please find the issue, thanks.

use render..

**Comment by SilentDemonSD** [comment]
> ![image](https://github.com/SilentDemonSD/FZBypassBot/assets/78243989/a0e7f625-753a-428b-8287-7315e88e55a6)
> 
> please find the issue, thanks.

Use SilentDemonSD/pyTele-Loader -> Koyeb Deploy and Set REPO as FZBypassBot
