### ISSUE TITLE
Getting NoneType' object has no attribute 'findAll' when deploying on heroku

### ISSUE THREAD

**Issue by Vinzgh24** [SilentDemonSD/FZBypassBot#40]
Tried to bypass some link and getting error with NoneType' object has no attribute 'findAll'

This happen on heroku but works fine on my local environment.

**Comment by SilentDemonSD** [comment]
> Tried to bypass some link and getting error with NoneType' object has no attribute 'findAll'
> 
> This happen on heroku but works fine on my local environment.

Can you provide screenshots or some references like which link you tried and  what happened next ?
